[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "chest_xray_pneumonia_detector"
version = "0.1.0"
requires-python = ">=3.8"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["chest_xray_pneumonia_detector"]
py-modules = [
    "architecture_review",
    "data_loader",
    "data_split",
    "evaluate",
    "grad_cam",
    "inference",
    "model_builder",
    "predict_utils",
    "dataset_stats",
    "train_engine",
    "version_cli",
    "performance_benchmark",
    "model_architecture_validation",
    "dependency_security_scan",
]

[project.scripts]
cxr-version = "version_cli:main"
cxr-dataset-stats = "dataset_stats:main"
cxr-benchmark = "performance_benchmark:main"
cxr-validate = "model_architecture_validation:main"
cxr-security-scan = "dependency_security_scan:main"
