name: 🔒 Security Vulnerability Report
description: Report a security vulnerability (private issues only)
title: "[SECURITY] "
labels: ["security", "vulnerability"]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ IMPORTANT: Do not report security vulnerabilities in public issues.**
        
        If this is a security vulnerability, please report it privately by emailing the maintainers instead of creating a public issue.
        
        For non-security bugs, please use the Bug Report template instead.

  - type: checkboxes
    id: confirmation
    attributes:
      label: Confirmation
      description: Please confirm this is not a security vulnerability
      options:
        - label: I confirm this is NOT a security vulnerability and can be discussed publicly
          required: true

  - type: textarea
    id: description
    attributes:
      label: Issue Description
      description: Since you've confirmed this is not a security issue, please describe the problem
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Step one...
        2. Step two...
        3. Step three...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this issue?
      options:
        - Low
        - Medium
        - High
        - Critical
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide details about your environment:
        - OS
        - Python version
        - Package version
        - Docker version (if applicable)
      placeholder: |
        - OS: Ubuntu 20.04
        - Python: 3.10
        - Package version: 0.2.0
        - Docker: 20.10.12
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional information that might be helpful